### ISSUE TITLE
Storyline

### ISSUE THREAD

**Issue by Mstrlow** [Raildex/Asteroids#11]

**Comment by 0xxym0r0n** [comment]
#### Erster Entwurf:
##### ----- PROLOG ------
Captain <Name einfügen> befindet sich auf dem Weg, abgebautes Avanium
zu seiner Raumstation zu bringen. 

// wenn gewollt hier noch ein Funkgespräch zwischen <Name einfügen>
// und seiner Raumstation einfügen.

Captain <Name einfügen> gerät in einen Asteoridenschauer.
Um an den Asteroiden vorbei zu kommen muss er diese zerstören. Aber
die (bösen) Dedicaner haben auch interesse an dem Avanium und wollen es
von Captain <Name einfügen> holen.

So beginnt eine hetzjagt gegen Asteroiden und den Truppen der Dedicaner.

// könnte man je level noch präziser machen mit vorstellung der levelendbosse
