### ISSUE TITLE
Asteroid

### ISSUE THREAD

**Issue by wikiniki** [Raildex/Asteroids#9]
Erstellen eines Asteroid-Objekts mit einer entsprechenden Kollisionsbox

**Comment by 0xxym0r0n** [comment]
-Es fehlt: Kollision 

-Richtungsvektor und rotationsgeschwingigkeitmuss in konstruktor übergeben werden

**Comment by 0xxym0r0n** [comment]
Grafik muss im konstuktor übergeben werden

**Comment by 0xxym0r0n** [comment]
-Es fehlt: Optimierungen
